# Logging configuration for detailed debugging
logging:
  level: "DEBUG"         # Use DEBUG to see every detail during your first test run.
  directory: "logs"

# Trading tasks for your FARMER_001 wallet
tasks:
  - wallet_name: "FARMER_001"
    market_symbol: "ETH-USD-PERP" # A liquid market, good for testing.
    strategy_name: "vamp_mm"
    strategy_params:
      # CRITICAL: Paradex requires minimum $100 USD per order
      # This is the minimum allowed by the exchange
      order_value: 100

      # Use a wider spread for testing. This makes it less likely you get filled instantly,
      # giving you more time to observe the bot's quoting behavior. 25 bps = 0.25%
      base_spread_bps: 25

      # A strong skew helps manage risk quickly if you get a fill on a small account.
      inventory_skew_bps: 20

      # Slow down the refresh rate so you can easily read the logs in real-time.
      # 2000ms = 2 seconds between each quote update.
      refresh_frequency_ms: 2000