# Logging configuration for detailed debugging
logging:
  level: "DEBUG"         # Use DEBUG to see every detail during your first test run.
  directory: "logs"

# Trading tasks for your FARMER_001 wallet
tasks:
  - wallet_name: "FARMER_001"
    market_symbol: "ETH-USD-PERP" # A liquid market, good for testing.
    strategy_name: "vamp_mm"
    strategy_params:
      # Using $105 order value to reduce number of trades
      order_value: 105
      # Use positive spread to protect against losses
      base_spread_bps: 0

      # A strong skew helps manage risk quickly if you get a fill on a small account.
      inventory_skew_bps: 20

      # 30-second refresh interval to avoid POST_ONLY_WOULD_CROSS
      refresh_frequency_ms: 30000

      # Only reprice if new quote differs by this threshold (in bps)
      reprice_threshold_bps: 5
      
      # Maximum orders per side (1 = only 1 buy and 1 sell order max)
      max_orders_per_side: 1
      
      # Leverage setting (5x or 10x instead of default 50x)
      leverage: 10

    # Optional hedging configuration (for delta-neutral automation)
    hedge:
      enabled: true
      exchange: "hyperliquid"    # currently supports 'hyperliquid'
      symbol_map:
        ETH-USD-PERP: "ETH"      # example mapping for Hyperliquid (ETH-USD-PERP -> ETH)
      mode: "market"             # or "limit"
      slippage_bps: 10