# Logging configuration for detailed debugging
logging:
  level: "DEBUG"         # Use DEBUG to see every detail during your test run.
  directory: "logs"

# Trading tasks for your FARMER_001 wallet
tasks:
  - wallet_name: "FARMER_001"
    # Using DOGE-USD-PERP as it exists on both exchanges
    market_symbol: "DOGE-USD-PERP"
    strategy_name: "vamp_mm"
    strategy_params:
      # --- Core Strategy Params ---
      order_value: 20               # Start with a very small order value for testing ($20)
      base_spread_bps: 30           # Use a wider spread for safety during testing
      inventory_skew_bps: 20
      
      # --- Teammate's New Params (MERGED) ---
      refresh_frequency_ms: 30000   # Slower 30-second refresh to avoid errors
      max_orders_per_side: 1        # Place only one buy and one sell order at a time
      leverage: 10                  # Set leverage on Paradex to 10x for this market

    # --- Hedging Configuration for Paradex <-> Lighter ---
    hedge:
      enabled: true
      exchange: "lighter"             # CRITICAL: This enables the new Lighter integration
      symbol_map:
        # Mapping Paradex symbol to the Lighter symbol format (e.g., 'DOGE')
        DOGE-USD-PERP: "DOGE"
      mode: "market"                  # Use market orders for instant hedging
      slippage_bps: 50                # Allow 0.5% slippage for market orders